# Sprawozdanie 5 - Dominik Kołodziej

Zadanie 1

$\left[\begin{matrix}
1 & 1 \\
1 & 1.0001\\
\end{matrix}\right] \cdot 
\left[\begin{matrix}
x_1 \\
x_2\\
\end{matrix}\right]
=
\left[\begin{matrix}
2 \\
2.0001\\
\end{matrix}\right]
$
$
\quad
$
$
\left\{ \begin{array}{l}
x_1+x_2=2\\
x_1+1.0001x_2=2.0001
\end{array} \right.
$
$
\quad
$
$
\left\{ \begin{array}{l}
x_1=1\\
x_2=2
\end{array} \right.
$
<br>

$\left[\begin{matrix}
1 & 1 \\
1 & 1.0001\\
\end{matrix}\right] \cdot 
\left[\begin{matrix}
x_1 \\
x_2\\
\end{matrix}\right]
=
\left[\begin{matrix}
2 \\
2\\
\end{matrix}\right]
$
$
\quad
$
$
\left\{ \begin{array}{l}
x_1+x_2=2\\
x_1+1.0001x_2=2
\end{array} \right.
$
$
\quad
$
$
\left\{ \begin{array}{l}
x_1=2\\
x_2=0
\end{array} \right.
$
<br><br>
$||A||=2,0001$
<br><br>
$A^{-1} = \left[\begin{matrix}
10001 & -10000 \\
-10000 & 10000\\
\end{matrix}\right]$
<br><br>
$||A^{-1}||=200001$
<br><br>
$cond(A)=400022,0001$

In [1]:
#zadanie 2
import numpy as np

def matrix_norm_max(mac):
    maxx=mac[0][0]
    for r in range (len(mac)):
        for c in range(len(mac[r])):
            if mac[r][c]>maxx:
                maxx=mac[r][c]
    return maxx;

def gen_hilb(n):
    macierzH=np.zeros((n,n))
    for r in range(n):
        for c in range(n):
            macierzH[r][c]=1/(r+c+1)
    return macierzH
        
H=gen_hilb(8)
print("Norma kolumnowa: " , np.linalg.cond(H,1))
print("Norma wierszowa: " , np.linalg.cond(H,np.inf))
print("Norma spektralna: " , np.linalg.cond(H,2))

print("Normy macierzowe wychodzą bardzo dużej wielkości, dlatego można powiedzieć, że macierz Hilberta jest przykładem macierzy źle uwarunkowanej")


Norma kolumnowa:  33872792384.49069
Norma wierszowa:  33872792385.924484
Norma spektralna:  15257575538.060041
Normy macierzowe wychodzą bardzo dużej wielkości, dlatego można powiedzieć, że macierz Hilberta jest przykładem macierzy źle uwarunkowanej


In [2]:
#zadanie 3
import math
import scipy as sc
import scipy.misc
import time

n=20
t=np.linspace(0,1,n)
b=[]
for i in t:
    b.append(4*math.cos(i))
A=np.fliplr(np.vander(t,n))

naglowki = [" ", "solve","qr", "domyslna"]
czasy=["czasy","","",""]
normy=["normy","","",""]

### 1. metoda solve
suma=0
for i in range (1000):
    start = time.clock()
    x_solve=np.linalg.solve(A,b)
    end=time.clock()
    czas=end-start
    suma+=czas
srednia=str(suma/1000)
czasy[1]=srednia
norm=np.linalg.norm(np.subtract(b,np.matmul(A,x_solve)))
normy[1]=str(norm)

### 2. metoda QR
suma=0
for i in range (1000):
    start = time.clock()
    q, r = np.linalg.qr(A)
    x_trian=sc.linalg.solve_triangular(r, np.matmul(np.linalg.inv(q),b))
    end=time.clock()
    czas=end-start
    suma+=czas
srednia=str(suma/1000)
czasy[2]=srednia
norm=np.linalg.norm(np.subtract(b,np.matmul(A,x_trian)))
normy[2]=str(norm)

### 3. domyślna metoda
suma=0
for i in range (1000):
    start = time.clock()
    x_default=np.linalg.lstsq(A,b,rcond=1)[0]
    end=time.clock()
    czas=end-start
    suma+=czas
srednia=str(suma/1000)
czasy[3]=srednia
norm=np.linalg.norm(np.subtract(b,np.matmul(A,x_default)))
normy[3]=str(norm)

for n in naglowki:
    print ('%22s' % n, end=' ')
print()

for n in czasy:
    print ('%22s' % n[:22], end=' ')
print()
for n in normy:
    print ('%22s' % n[:22], end=' ')





                                        solve                     qr               domyslna 
                 czasy  0.0003209059999999995  0.0012410930000000078  0.0005099429999999953 
                 normy  2.220446049250313e-15  7.119291619286993e-15 1.7404671430534633e-14 

In [3]:
# zadanie 4




import matplotlib.pyplot as plt
import scipy.sparse.linalg


n = 500
tau = [0.01, 0.05, 0.1, 2, 0.5, 0.75]
b = np.random.uniform(-1,1,n)

Pom = np.tril(np.random.uniform(-1,1,(n,n)))
Pom = np.add(Pom,np.transpose(Pom))
Pom = np.subtract(Pom, np.diag(np.diag(Pom)))
Pom = np.add(Pom,np.diag(np.diag(np.ones((n,n)))))


A=[]
for t in range (len(tau)):
    A.append(Pom.copy())
    
for t in range (len(tau)):
    for r in range (n):
        for c in range (n):
            if r!=c:
                if abs(Pom[r][c])>tau[t]:
                    A[t][r][c]=0

wsp=[]
for t in range (len(tau)):
    wsp.append(np.linalg.cond(A[t],1))
    

plt.plot(tau,wsp,'o')
plt.xlabel('tau')
plt.title('Uwarunkowanie macierzy')
plt.ylabel('wspołczynnik uwarunkowania macierzy')
plt.grid(True)
plt.show()

### Rozwiązywanie układu równań
# 1. metoda solve
x_solve=[]
x_solve_czasy=[]
x_solve_normy=[]

for t in range (len(tau)):
    start = time.clock()
    x_temp=np.linalg.solve(A[t],b)
    end=time.clock()
    x_solve.append(x_temp)
    x_solve_czasy.append(end-start)
    x_solve_normy.append(np.linalg.norm(np.subtract(b,np.matmul(A,x_temp))))

# 2. metoda bicg
x_bicg=[]
x_bicg_czasy=[]
x_bicg_normy=[]
for t in range (len(tau)):
    start = time.clock()
    
    x_csr=scipy.sparse.csr_matrix(A[t]).toarray()
    x_temp=sc.sparse.linalg.bicg(x_csr,b)[0]
    
    end=time.clock()
    x_bicg.append(x_temp)
    x_bicg_czasy.append(end-start)
    x_bicg_normy.append(np.linalg.norm(np.subtract(b,np.matmul(A,x_temp))))
    
# 3. metoda gmres
x_gmres=[]
x_gmres_czasy=[]
x_gmres_normy=[]

for t in range (len(tau)):
    start = time.clock()
    
    #oblicznanie tej macierzy zajmuje sporo czasu, dlatego proszę o cierpliwość
    x_csr=scipy.sparse.csr_matrix(A[t]).toarray()
    x_temp=sc.sparse.linalg.gmres(x_csr,b)[0]
    
    end=time.clock()
    x_gmres.append(x_temp)
    x_gmres_czasy.append(end-start)
    x_gmres_normy.append(np.linalg.norm(np.subtract(b,np.matmul(A,x_temp))))


    
### Rysowanie dwóch ostatnich wykresów
    
plt.plot(tau,x_solve_czasy,'o')
plt.plot(tau,x_bicg_czasy,'o')
plt.plot(tau,x_gmres_czasy,'o')
plt.legend(['solve','bicg','gmres'])
plt.title('Porównanie czasów')
plt.xlabel('tau')
plt.ylabel('czas obliczeń [s]')
plt.grid(True)
plt.show()


plt.plot(tau,x_solve_normy,'o')
plt.plot(tau,x_bicg_normy,'o')
plt.plot(tau,x_gmres_normy,'o')
plt.legend(['solve','bicg','gmres'])
plt.title('Normy macierzowe')
plt.xlabel('tau')
plt.ylabel('normy')
plt.grid(True)
plt.show()


<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

In [4]:
# zadanie 5

def maxA(A):
    maxx=A[0]
    for i in A:
        if i>maxx:
            maxx=i
    return maxx

def GaussSeidl(A, b, d=0.001):
    
    diff = 1;
    x=[]
    for i in range(len(A)):
        x.append(1)
    
    LD = np.tril(A)
    U = A - LD
    
    MGS=np.dot(-np.linalg.inv(LD),U)
    
    w_wlasne=np.linalg.eigvals(MGS)
    pr_spek=np.amax(w_wlasne)
    if(pr_spek>1):
        return "NIE MOŻNA ZASTOSOWAĆ TEJ METODY - promień spektralny macierzy MGS jest większy od 1"
    
    while (diff>d):
        x_prev = x
        x = np.add(np.dot(MGS, x),np.dot(-np.linalg.inv(LD),b))
        diff=abs(maxA(x_prev)-maxA(x))
        
    return -x

n = 18


A = np.array([[4.0, -2.0, 1.5], [1.0, -3.0, 2.0], [-1.0, 2.0, 6.0]])
b = [1.0, 2.0, 3.0]
print (GaussSeidl(A, b))
print (sc.linalg.solve(A, b))

A_2 = [[1, 2, 3], [2, 1, 3], [3, 2, 1]]
b_2 = [1, 2, 0]
print (GaussSeidl(A_2, b_2))
print (sc.linalg.solve(A_2, b_2))

[-0.12868962 -0.31997839  0.58521119]
[-0.1292517  -0.31972789  0.58503401]
NIE MOŻNA ZASTOSOWAĆ TEJ METODY - promień spektralny macierzy MGS jest większy od 1
[ 0.25 -0.75  0.75]
